app:
  port: ':4200'
  cert_file: './cmd/api/certificate.pem'
  key_file: './cmd/api/key.pem'
  time_format: '2006-01-02T15:04:05'

producer:
  brokers: ['192.168.0.105:9092']
  topic: 'store.match.match'
  batch_size: 1
  batch_timeout: 10

es:
  host: 'localhost'
  port: '9200'
  cluster: superheromatch
  index: superhero
  batch_size: 50

cache:
  address: 'localhost'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  match_key_format: 'suggestion.%s'